### ISSUE TITLE
Warnings on settings page

### ISSUE THREAD

**Issue by ravibpatel** [artprojectgroup/woocommerce-apg-sms-notifications#10]
I am getting warnings on settings page as shown [here](https://www.screenpresso.com/=ub1Ff). It goes away after I do the settings and save it. Upon debugging, I found that $mensajes variable on [this line](https://github.com/artprojectgroup/woocommerce-apg-sms-notifications/blob/master/includes/formulario.php#L148) doesn't exist when you start it for the first time.

**Comment by artprojectgroup** [comment]
Thank you for the advice.

Fixed in the next update.

Kind regards.
