### ISSUE TITLE
PHP notices

### ISSUE THREAD

**Issue by webdados** [artprojectgroup/woocommerce-apg-sms-notifications#7]
Here are some PHP notices that should be fixed:

Notice: Undefined index: mensaje_fallido in /.../wp-content/plugins/woocommerce-apg-sms-notifications/includes/admin/funciones-formulario.php on line 11

Notice: Undefined index: mensaje_devuelto in /.../wp-content/plugins/woocommerce-apg-sms-notifications/includes/admin/funciones-formulario.php on line 15

Notice: Undefined index: mensaje_cancelado in /.../wp-content/plugins/woocommerce-apg-sms-notifications/includes/admin/funciones-formulario.php on line 16

**Comment by webdados** [comment]
Yes, that "fixes" it, but I think you still should address the notices, that's why I used github and not the support forum on .org :-)

**Comment by webdados** [comment]
Also several of these:

[29-May-2020 15:05:20 UTC] woocommerce_add_order_item_meta is deprecated since version 3.0.0! Use woocommerce_new_order_item instead.

**Comment by artprojectgroup** [comment]
Where?

**Comment by webdados** [comment]
Sorry, wrong plugin. My bad.

**Comment by artprojectgroup** [comment]
Ok :-)

**Comment by artprojectgroup** [comment]
Fixed in the next update.
